blog/urls.py
from django.conf.urls import url

from .views import (
    BlogView,
    BlogDetailView,
    BlogCreateView,
    BlogUpdateView,
    BlogDeleteView,
)

urlpatterns = [
    url(r'update/(?P<pk>\d+)/$', BlogUpdateView.as_view(),name='update'),
    url(r'delete/(?P<pk>\d+)/$', BlogDeleteView.as_view(),name='delete'),
    url(r'(?P<pk>\d+)/$', BlogDetailView.as_view(), name='detail'),
    url(r'create/$', BlogCreateView.as_view(), name='create'),
    url(r'$', BlogView.as_view(), name='template'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url
from django.conf.urls import include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = []
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += [
    url('^post/', include(('post.urls','post'),namespace = 'post')),
    url('^blog/', include(('blog.urls','blog'),namespace = 'blog')),
    path('admin/', admin.site.urls),
    url('^', include(('landing.urls','landing'),namespace = 'landing')),
]

post/urls.py
from django.conf.urls import url

from .views import (
    PostView,
    PostDetailView,
    PostCreateView,
    PostDeleteView,
    PostUpdateView,
)

urlpatterns = [
    url(r'delete/(?P<pk>\d+)/$', PostDeleteView.as_view(),name='delete'),
    url(r'update/(?P<pk>\d+)/$', PostUpdateView.as_view(),name='update'),
    url(r'(?P<pk>\d+)/$', PostDetailView.as_view(), name='detail'),
    url(r'create/$', PostCreateView.as_view(), name='create'),
    url(r'$', PostView.as_view(), name='template'),
]

post/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
# Create your models here.
CATEGORY_CHOICES = (
    (1, ("Kuca")),
    (2, ("Zgrada")),
    (3, ("Hotel")),
    (4, ("Restoran")),
)

class Post(models.Model):
    name = models.CharField(max_length=100, unique = True)
    description = models.CharField(max_length=4000)
    category = models.IntegerField(choices=CATEGORY_CHOICES, default=1)
    date = models.DateField()
    created = models.DateTimeField(auto_now_add=True)
    REQUIRED_FIELDS = ['name','date','description','category']
    def __str__(self):
        return self.name
    def get_absolute_url(self):
        return reverse('post:detail', kwargs={'pk': self.pk})

class Images(models.Model):
    post = models.ForeignKey(Post, default=None,on_delete=models.CASCADE)
    image = models.ImageField(upload_to="images/",verbose_name='Image')

post/forms.py
from .models import Post,Images,CATEGORY_CHOICES
from django import forms

class PostForm(forms.ModelForm):
    description = forms.CharField(widget=forms.Textarea)
    category = forms.ChoiceField(choices = CATEGORY_CHOICES, label="", initial='', widget=forms.Select(), required=True)
    class Meta:
        model = Post
        fields = ['name','description','date','category']
    def __init__(self, *args, **kwargs):
        super(PostForm, self).__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = 'form-control'

        self.fields['date'].widget.attrs['placeholder'] = 'YYYY-MM-DD'
        self.fields['description'].widget.attrs['placeholder'] = 'Ovdje ide tekst....'

class ImageForm(forms.ModelForm):
    image = forms.ImageField(label='Image')
    class Meta:
        model = Images
        fields = ('image', )

    def __init__(self, *args, **kwargs):
        super(ImageForm, self).__init__(*args, **kwargs)
        self.fields['image'].widget.attrs['class'] = 'form-control-file'
        self.fields['image'].widget.attrs['multiple'] = True

post/views.py
from django.shortcuts import render
from django.views import generic
from .forms import PostForm,ImageForm
from .models import Post,Images,CATEGORY_CHOICES
from django.conf import settings
from django.urls import reverse_lazy
from django.http import HttpResponse

class PostView(generic.ListView):
    template_name = "post/post.html"
    model = Post
    def get_queryset(self):
        queryset = []
        posts = Post.objects.all()
        for post in posts:
            post.image = Images.objects.filter(post = post).first().image
            queryset.append(post)
        return queryset

class PostDetailView(generic.DetailView):
    model = Post
    def get_context_data(self, **kwargs):
        object = super().get_context_data(**kwargs)
        object['object'].category = CATEGORY_CHOICES[object['object'].category-1][1]
        object['object'].images = []
        for image in Images.objects.filter(post = object["object"]).all():
            object['object'].images.append(image.image)
        return object

class PostCreateView(generic.edit.CreateView):
    template_name = "post/post_form.html"
    form_class = PostForm

    def get_context_data(self, **kwargs):
        object = super().get_context_data(**kwargs)
        object["image_form"] = ImageForm(None)
        return object

    def post(self, request, *args, **kwargs):
        post_form = PostForm(request.POST)
        image_form = ImageForm(request.POST, request.FILES)
        if post_form.is_valid() and image_form.is_valid():
            post = post_form.save()
            for image in request.FILES.getlist('image'):
                instance = Images(post=post, image=image)
                instance.save()
        return super(PostCreateView, self).form_valid(post_form)


class PostUpdateView(generic.edit.UpdateView):
    model = Post
    form_class = PostForm
    template_name_suffix = '_update_form'

    def get_context_data(self, **kwargs):
        object = super().get_context_data(**kwargs)
        object["image_form"] = ImageForm(None)
        return object

    def post(self, request, *args, **kwargs):
        image_form = ImageForm(request.POST, request.FILES)
        post = Post.objects.get(pk = self.kwargs['pk'])
        if image_form.is_valid():
            for image in Images.objects.filter(post = post).all():
                image.delete()

            for image in request.FILES.getlist('image'):
                instance = Images(post=post, image=image)
                instance.save()
        return super(PostUpdateView, self).post(self, request, *args, **kwargs)

class PostDeleteView(generic.edit.DeleteView):
    model = Post
    success_url = reverse_lazy('post:template')

post/templates/post/post.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<div id="fh5co-main">
    <div class="fh5co-narrow-content">
        <h2 class="fh5co-heading">Portfolio</h2>
        <div class="row row-bottom-padded-md">
            {% for obj in object_list %}
            <div class="col-md-4 col-sm-6 col-padding text-center animated fadeIn">
                <a href="{{ obj.get_absolute_url }}" class="work" style="background-image: url('{{ obj.image.url }}');">
                    <div class="desc">
                        <h3>{{ obj.name }}</h3>
                        <span>{{ obj.description|truncatechars:100 }}</span>
                    </div>
                </a>
            </div>
            {% endfor %}
        </div>
    </div>
    {% if user.is_superuser %}
    <div class="fh5co-narrow-content">
        <a href="{% url 'post:create' %}" class="btn btn-primary">Create Post</a>
    </div>
    {% endif %}
</div>
{% endblock %}

post/templates/post/post_confirm_delete.html
{% extends "base.html" %}

{% block content %}
<div id="fh5co-main">
    <div class="fh5co-narrow-content">
        <div class="row col-md-4 col-md-offset-2">
            <h1>Post delete form</h1>
            <h4>Are you sure you want to delete?</h4>
            <h4>{{ object.name }}</h4>
            <h4>{{ object.description }}</h4>
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %} {{ form.as_p }}
                <input type="submit" class="btn btn-primary" value="Delete">
            </form>
        </div>
    </div>
</div>
{% endblock %}

post/templates/post/post_detail.html
{% extends "base.html" %}
{% load static %}

{% block content %}

<div id="fh5co-main">
  <div class="fh5co-narrow-content">
    <div class="row">
      <div class="col-md-8 col-md-offset-1 animated fadeIn" data-animate-effect="fadeInLeft">
        <div id="myCarousel" class="carousel slide" data-ride="carousel">
          <!-- Indicators -->
          <ol class="carousel-indicators">
            {% for image in object.images %}
            {% if forloop.first %}
                <li data-target="#myCarousel" data-slide-to="{{ forloop.counter0 }}" class="active"></li>
            {% else %}
                <li data-target="#myCarousel" data-slide-to="{{ forloop.counter0 }}"></li>
            {% endif %}
            {% endfor %}
          </ol>
          <!-- Wrapper for slides -->
          <div class="carousel-inner">
            {% for image in object.images %}
            {% if forloop.first %}
                <div class="item active">
            {% else %}
                <div class="item">
            {% endif %}
              <img class="img-responsive" data-enlargable src="{{ image.url }}" style="width:96%!important;">
            </div>
            {% endfor %}
          </div>
      </div>
    </div>
    </div>
    <div class="row mt">
      <div class="col-md-8 col-md-offset-1 animated fadeIn" data-animate-effect="fadeInLeft">
        <h2 class="fh5co-heading">About Company</h2>
        <p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Quisque sit amet efficitur nih. Interdum et malesuada fames ac ante ipsum primis in faucibus interda et malesuada parturient.</p>
        <p>Odavno je uspostavljena činjenica da čitača ometa razumljivi tekst dok gleda raspored elemenata na stranici. Smisao korištenja Lorem Ipsum-a jest u tome što umjesto 'sadržaj ovjde, sadržaj ovjde' imamo normalni raspored slova i riječi, pa čitač ima dojam da gleda tekst na razumljivom jeziku. Mnogi programi za stolno izdavaštvo i uređivanje web stranica danas koriste Lorem Ipsum kao zadani model teksta, i ako potražite 'lorem ipsum' na Internetu, kao rezultat dobit ćete mnoge stranice u izradi.
        </p><p>
        Kada je nepoznati tiskar uzeo tiskarsku galiju slova i posložio ih da bi napravio knjigu s uzorkom tiska. Taj je tekst ne samo preživio pet stoljeća, već se i vinuo u svijet elektronskog slovoslagarstva, ostajući u suštini nepromijenjen. Postao je popularan tijekom 1960-ih s pojavom Letraset listova s odlomcima Lorem </p>
      </div>
    </div>
    <div class="row">
      <div class="col-md-8 col-md-offset-1">
      {% if user.is_superuser %}
      <div class="project-info">
        <a class="btn btn-primary" href="{% url 'post:update' pk=object.id %}">Update</a>
        <a class="btn btn-primary" href="{% url 'post:delete' pk=object.id %}">Delete</a>
      </div>
      {% endif %}
      </div>
    </div>
  </div>
</div>

{% endblock %}

post/templates/post/post_form.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<div id="fh5co-main">
    <div class="fh5co-narrow-content">
        <div class="row col-md-6 col-md-offset-2 bp">
            <h1>Post form</h1>
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %} {{ form.as_p }}
                {{ image_form.as_p }}
                <input name="submit" type="submit" class="form-control" id="submit" value="Submit a article">
            </form>
        </div>
    </div>
</div>
{% endblock %}

post/templates/post/post_update_form.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<div id="fh5co-main">
    <div class="fh5co-narrow-content">
        <div class="row col-md-6 col-md-offset-2">
            <h1>Post update form</h1>
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %} {{ form.as_p }}
                {{ image_form.as_p }}
                <input name="submit" type="submit" class="form-control" id="submit" value="Submit a article">
            </form>
        </div>
    </div>
</div>
{% endblock %}