blog/urls.py
from django.conf.urls import url

from .views import (
    BlogView,
    BlogDetailView,
    BlogCreateView,
    BlogUpdateView,
    BlogDeleteView,
)

urlpatterns = [
    url(r'update/(?P<pk>\d+)/$', BlogUpdateView.as_view(),name='update'),
    url(r'delete/(?P<pk>\d+)/$', BlogDeleteView.as_view(),name='delete'),
    url(r'(?P<pk>\d+)/$', BlogDetailView.as_view(), name='detail'),
    url(r'create/$', BlogCreateView.as_view(), name='create'),
    url(r'$', BlogView.as_view(), name='template'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url
from django.conf.urls import include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = []
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += [
    url('^post/', include(('post.urls','post'),namespace = 'post')),
    url('^blog/', include(('blog.urls','blog'),namespace = 'blog')),
    path('admin/', admin.site.urls),
    url('^', include(('landing.urls','landing'),namespace = 'landing')),
]

blog/models.py
from django.db import models
from django.urls import reverse
from .validators import alpha
# Create your models here.
class Blog(models.Model):
    name = models.CharField(max_length=100, unique = True)
    text = models.CharField(max_length=10000)
    likes = models.IntegerField(default=0)
    date = models.DateField()
    created = models.DateTimeField(auto_now_add=True)
    image = models.ImageField(upload_to="images/",verbose_name='Image')
    REQUIRED_FIELDS = ['name','date','text','image']
    def __str__(self):
        return self.name
    def get_absolute_url(self):
        return reverse('blog:detail', kwargs={'pk': self.pk})

blog/forms.py
from .models import Blog
from django import forms

class BlogForm(forms.ModelForm):
    class Meta:
        model = Blog
        fields = ['name','date','text','image' ]
        widgets = {
            'text': forms.Textarea(attrs={'rows': 5}),
        }

    def __init__(self, *args, **kwargs):
        super(BlogForm, self).__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = 'form-control'

        self.fields['name'].widget.attrs['placeholder'] = 'Name'
        self.fields['date'].widget.attrs['placeholder'] = 'YYYY-MM-DD'
        self.fields['text'].widget.attrs['placeholder'] = 'Ovdje ide tekst....'
        self.fields['image'].widget.attrs['class'] = 'form-control-file'

blog/views.py
from django.shortcuts import render
from django.views import generic
from .models import Blog
from .forms import BlogForm
from django.urls import reverse_lazy
# Create your views here.

class BlogView(generic.ListView):
    template_name = "blog/blog.html"
    model = Blog

class BlogDetailView(generic.DetailView):
    model = Blog
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context

class BlogCreateView(generic.edit.CreateView):
    template_name = "blog/blog_form.html"
    form_class = BlogForm

class BlogUpdateView(generic.edit.UpdateView):
    form_class = BlogForm
    model = Blog
    template_name = 'blog/blog_form.html'

class BlogDeleteView(generic.edit.DeleteView):
    model = Blog
    success_url = reverse_lazy('blog:template')
    template_name = "blog/confirm_delete.html"

blog/templates/blog/blog.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<div class="event__search__floater">
    <div class="search__anchor">
        <form id="event-search-form">
            <input id="Search" type="text" class="search__bar" onkeyup="myFunction()" placeholder="Search Event">
            <div class="search__toggler"></div>
        </form>

    </div>
</div>
<div id="fh5co-main">
    <div class="fh5co-narrow-content">
        <h2 class="fh5co-heading animated fadeIn">Read Our Blog</h2>
        <div class="row row-bottom-padded-md">
            {% for obj in object_list %}
            <div class="col-md-4 col-sm-6 col-padding animated fadeIn blog-name" value="{{ obj.pk }}" id="blog_{{ obj.pk }}">
                <div class="blog-entry">
                    <a href="{{ obj.get_absolute_url }}" class="blog-img"><img src="{{ obj.image.url }}" class="img-responsive"></a>
                    <div class="desc">
                        <h3><a href="{{ obj.get_absolute_url }}">{{obj.name}}</a></h3>
                        <span><small>by Admin </small> / <small> Web Design </small> / <small> <i class="icon-comment"></i> 14</small></span>
                        <p>Design must be functional and functionality must be translated into visual aesthetics</p>
                        <a href="{{ obj.get_absolute_url }}" class="lead">Read More <i class="icon-arrow-right3"></i></a>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
        {% if user.is_superuser %}
        <a href="{% url 'blog:create' %}" class="btn btn-primary">Create Blog</a>
        {% endif %}
    </div>
</div>
{% endblock %}

blog/templates/blog/blog_detail.html
{% extends "base.html" %}
{% load static %}
{% load nbsp %}

{% block content %}
<div id="fh5co-main">
    <div class="fh5co-narrow-content">
        <div class="row">
            <div class="col-md-8 col-md-offset-1 animated fadeIn" data-animate-effect="fadeInLeft">
                <img class="img-responsive" src="{{ object.image.url }}" alt="Free HTML5 Bootstrap Template by FreeHTML5.co">
            </div>
        </div>
        <div class="row mt">
            <div class="col-md-8 col-md-offset-1 animated fadeIn" data-animate-effect="fadeInLeft">
                <h2 class="fh5co-heading">About Company</h2>
                {% autoescape off %}
                <p>{{ object.text|linebreaksbr|nbsp }}</p>
                {% endautoescape %}
            </div>
        </div>
        <div class="row">
            <div class="col-md-8 col-md-offset-1 mt">
                {% if user.is_superuser %}
                <a class="btn btn-primary" href="{% url 'blog:update' pk=object.id %}">Update</a>
                <a class="btn btn-primary" href="{% url 'blog:delete' pk=object.id %}">Delete</a>
                {% endif %}
            </div>
        </div>
    </div>
</div>
{% endblock %}

blog/templates/blog/blog_form.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<div id="fh5co-main">
    <div class="fh5co-narrow-content">
        <div class="row col-md-6 col-md-offset-2">
            <h1>Blog form</h1>
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %} {{ form.as_p }}
                <input name="submit" type="submit" class="form-control" id="submit" value="Submit a article">
            </form>
        </div>
    </div>
</div>
{% endblock %}

blog/templates/blog/confirm_delete.html
{% extends "base.html" %}

{% block content %}
<div id="fh5co-main">
    <div class="fh5co-narrow-content">
        <div class="row col-md-4 col-md-offset-2">
            <h1>Post delete form</h1>
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %} {{ form.as_p }}
                <input type="submit" class="btn btn-primary" value="Delete">
            </form>
        </div>
    </div>
</div>
{% endblock %}