blog/urls.py
from django.conf.urls import url

from .views import (
    BlogView,
    BlogDetailView,
    BlogCreateView,
    BlogUpdateView,
    BlogDeleteView,
)

urlpatterns = [
    url(r'update/(?P<pk>\d+)/$', BlogUpdateView.as_view(),name='update'),
    url(r'delete/(?P<pk>\d+)/$', BlogDeleteView.as_view(),name='delete'),
    url(r'(?P<pk>\d+)/$', BlogDetailView.as_view(), name='detail'),
    url(r'create/$', BlogCreateView.as_view(), name='create'),
    url(r'$', BlogView.as_view(), name='template'),
]

landing/urls.py
from django.conf.urls import url

from .views import (
    IndexView,
    AboutView,
    ContactView,
)

urlpatterns = [
    url(r'about$', AboutView.as_view(), name='about'),
    url(r'contact$', ContactView.as_view(), name='contact'),
    url(r'$', IndexView.as_view(), name='template'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url
from django.conf.urls import include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = []
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += [
    url('^post/', include(('post.urls','post'),namespace = 'post')),
    url('^blog/', include(('blog.urls','blog'),namespace = 'blog')),
    path('admin/', admin.site.urls),
    url('^', include(('landing.urls','landing'),namespace = 'landing')),
]

templates/base.html
<!DOCTYPE html> {% load static %}
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!-->
<html class="no-js">
<!--<![endif]-->

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Marble &mdash; Free HTML5 Bootstrap Website Template by FreeHTML5.co</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="Free HTML5 Website Template by FreeHTML5.co" />
    <meta name="keywords" content="free html5, free template, free bootstrap, free website template, html5, css3, mobile first, responsive" />
    <meta name="author" content="FreeHTML5.co" />
    <meta property="og:title" content="" />
    <meta property="og:image" content="" />
    <meta property="og:url" content="" />
    <meta property="og:site_name" content="" />
    <meta property="og:description" content="" />
    <meta name="twitter:title" content="" />
    <meta name="twitter:image" content="" />
    <meta name="twitter:url" content="" />
    <meta name="twitter:card" content="" />

    <!-- Place favicon.ico and apple-touch-icon.png in the root directory -->
    <link rel="shortcut icon" href="favicon.ico">

    <link href="https://fonts.googleapis.com/css?family=Roboto:100,300,400,500,700" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Baskervville&display=swap" rel="stylesheet">

    <!-- Animate.css -->
    <link rel="stylesheet" href="{% static 'css/animate.css' %}">
    <!-- Icomoon Icon Fonts-->
    <link rel="stylesheet" href="{% static 'css/icomoon.css' %}">
    <!-- Bootstrap  -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <!-- Flexslider  -->
    <link rel="stylesheet" href="{% static 'css/flexslider.css' %}">
    <!-- Theme style  -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}">

    <!-- Modernizr JS -->
    <script src="{% static 'js/modernizr-2.6.2.min.js' %}"></script>
    <!-- FOR IE9 below -->
    <!--[if lt IE 9]>
	<script src="js/respond.min.js"></script>
	<![endif]-->

</head>

<body>
    <div id="fh5co-page">
        <a href="#" class="js-fh5co-nav-toggle fh5co-nav-toggle"><i></i></a>
        <aside id="fh5co-aside" role="complementary" class="border js-fullheight">

            <h1 id="fh5co-logo"><a href="{% url 'landing:template' %}"></a>RN</h1>
            <nav id="fh5co-main-menu" role="navigation">
                <ul>
                    <li {% if "/" == request.path %}class="fh5co-active"{% endif %}><a href="{% url 'landing:template' %}">Home</a></li>
                    <li {% if "post" in request.path %}class="fh5co-active"{% endif %}><a href="{% url 'post:template' %}">Portfolio</a></li>
                    <li {% if "blog" in request.path %}class="fh5co-active"{% endif %}><a href="{% url 'blog:template' %}">Blog</a></li>
                    <li {% if "about" in request.path %}class="fh5co-active"{% endif %}><a href="{% url 'landing:about' %}">About</a></li>
                    <li {% if "contact" in request.path %}class="fh5co-active"{% endif %}><a href="{% url 'landing:contact' %}">Contact</a></li>
                </ul>
            </nav>

            <div class="fh5co-footer">
                <ul>
                    <li><a href="#"><i class="icon-facebook2"></i></a></li>
                    <li><a href="#"><i class="icon-twitter2"></i></a></li>
                    <li><a href="#"><i class="icon-instagram"></i></a></li>
                    <li><a href="#"><i class="icon-linkedin2"></i></a></li>
                </ul>
            </div>

        </aside>
        {% block content %} {% endblock %}
    </div>

    <!-- jQuery -->
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <!-- Bootstrap -->
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <!-- Waypoints -->
    <script src="{% static 'js/jquery.waypoints.min.js' %}"></script>
    <!-- Flexslider -->
    <script src="{% static 'js/jquery.flexslider-min.js' %}"></script>

    <!-- MAIN JS -->
    <script src="{% static 'js/main.js' %}"></script>

    <!-- Custom JS -->
    <script src="{% static 'js/custom.js' %}"></script>

</body>

</html>